name: busted

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: apt
      run: sudo apt-get install -y luarocks
    - name: busted install
      run: luarocks install --local busted

    - name: busted run metatool
      working-directory: ./metatool
      run: $HOME/.luarocks/bin/busted

    - name: busted run containertool
      working-directory: ./containertool
      run: $HOME/.luarocks/bin/busted
