name: mineunit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - id: mineunit-metatool
      uses: mt-mods/mineunit-actions@master
      with:
        working-directory: ./metatool
        badge-name: metatool-coverage
        badge-label: Metatool API Coverage
    - if: success()
      uses: peter-evans/commit-comment@v1.3.2
      with:
        body: |
          Test coverage report for Metatool API:
          ```
          ${{ steps.mineunit-metatool.outputs.mineunit-report }}
          ```
    - uses: RubbaBoy/BYOB@v1.2.0
      with:
        NAME: "${{ steps.mineunit-metatool.outputs.badge-name }}"
        LABEL: "${{ steps.mineunit-metatool.outputs.badge-label }}"
        STATUS: "${{ steps.mineunit-metatool.outputs.badge-status }}"
        COLOR: "${{ steps.mineunit-metatool.outputs.badge-color }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - id: mineunit-containertool
      uses: mt-mods/mineunit-actions@master
      with:
        working-directory: ./containertool
        badge-name: containertool-coverage
        badge-label: Containertool Coverage
    - if: success()
      uses: peter-evans/commit-comment@v1.3.2
      with:
        body: |
          Test coverage report for Containertool:
          ```
          ${{ steps.mineunit-containertool.outputs.mineunit-report }}
          ```
    - uses: RubbaBoy/BYOB@v1.2.0
      with:
        NAME: "${{ steps.mineunit-containertool.outputs.badge-name }}"
        LABEL: "${{ steps.mineunit-containertool.outputs.badge-label }}"
        STATUS: "${{ steps.mineunit-containertool.outputs.badge-status }}"
        COLOR: "${{ steps.mineunit-containertool.outputs.badge-color }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - id: mineunit-sharetool
      uses: mt-mods/mineunit-actions@master
      with:
        working-directory: ./sharetool
        badge-name: sharetool-coverage
        badge-label: Sharetool Coverage
    - if: success()
      uses: peter-evans/commit-comment@v1.3.2
      with:
        body: |
          Test coverage report for Sharetool:
          ```
          ${{ steps.mineunit-sharetool.outputs.mineunit-report }}
          ```
    - uses: RubbaBoy/BYOB@v1.2.0
      with:
        NAME: "${{ steps.mineunit-sharetool.outputs.badge-name }}"
        LABEL: "${{ steps.mineunit-sharetool.outputs.badge-label }}"
        STATUS: "${{ steps.mineunit-sharetool.outputs.badge-status }}"
        COLOR: "${{ steps.mineunit-sharetool.outputs.badge-color }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
