name: mineunit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - id: mineunit-metatool
      uses: mt-mods/mineunit-actions@badger
      with:
        working-directory: ./metatool
        badge-name: metatool-coverage
        badge-label: Metatool API Coverage
        badge-secret: ${{ secrets.MineunitBadgesKey }}

    - id: mineunit-containertool
      uses: mt-mods/mineunit-actions@badger
      with:
        working-directory: ./containertool
        badge-name: containertool-coverage
        badge-label: Containertool Coverage
        badge-secret: ${{ secrets.MineunitBadgesKey }}

    - id: mineunit-tubetool
      uses: mt-mods/mineunit-actions@badger
      with:
        working-directory: ./tubetool
        badge-name: tubetool-coverage
        badge-label: Tubetool Coverage
        badge-secret: ${{ secrets.MineunitBadgesKey }}

    - id: mineunit-sharetool
      uses: mt-mods/mineunit-actions@badger
      with:
        working-directory: ./sharetool
        badge-name: sharetool-coverage
        badge-label: Sharetool Coverage
        badge-secret: ${{ secrets.MineunitBadgesKey }}

    - if: success() && github.event_name == 'pull_request'
      uses: KeisukeYamashita/create-comment@v1
      with:
        check-only-first-line: true
        comment: |
          <details><summary><i>Click for detailed source code test coverage report</i></summary>
          
          ### Test coverage report for Metatool API sources:
          ```
          File                             Hits Missed Coverage
          -----------------------------------------------------
          ${{ steps.mineunit-metatool.outputs.mineunit-report }}
          ```
          ### Test coverage report for Containertool sources:
          ```
          File                             Hits Missed Coverage
          -----------------------------------------------------
          ${{ steps.mineunit-containertool.outputs.mineunit-report }}
          ```
          ### Test coverage report for Tubetool sources:
          ```
          File                             Hits Missed Coverage
          -----------------------------------------------------
          ${{ steps.mineunit-tubetool.outputs.mineunit-report }}
          ```
          ### Test coverage report for Sharetool sources:
          ```
          File                             Hits Missed Coverage
          -----------------------------------------------------
          ${{ steps.mineunit-sharetool.outputs.mineunit-report }}
          ```
          </details>
